import os

LLM_MODEL = "gemini-1.5-flash-002"
PROJECT_NUMBER = os.getenv("GCP_PROJECT_NUMBER")
SEARCH_ENGINE_ID= os.getenv("GCP_SEARCH_ENGINE_ID")
PROJECT_ID = os.getenv("GCP_PROJECT_ID")
BIGQUERY_DATASET_ID = os.getenv("GCP_BIGQUERY_DATASET_ID")
FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY") 

